//------------------------------------C O N S T A N T S----------------------------------------------
export const CategoryActionTypes = {
    CATEGORY_DATA_FIRST: '@@auth/CATEGORY_DATA_FIRST',
    CATEGORY_DATA_LOADING: '@@auth/CATEGORY_DATA_LOADING',
    CATEGORY_DATA_SUCCESS: '@@auth/CATEGORY_DATA_SUCCESS',
    CATEGORY_DATA_ERROR: '@@auth/CATEGORY_DATA_ERROR',
    CATEGORY_DATA_RESET: '@@auth/CATEGORY_DATA_RESET',

    SUB_CATEGORY_DATA_FIRST: '@@auth/SUB_CATEGORY_DATA_FIRST',
    SUB_CATEGORY_DATA_LOADING: '@@auth/SUB_CATEGORY_DATA_LOADING',
    SUB_CATEGORY_DATA_SUCCESS: '@@auth/SUB_CATEGORY_DATA_SUCCESS',
    SUB_CATEGORY_DATA_ERROR: '@@auth/SUB_CATEGORY_DATA_ERROR',

    CREATE_CATEGORY: 'CREATE_CATEGORY_FIRST',
    CREATE_CATEGORY_LOADING: 'CREATE_CATEGORY_LOADING',
    CREATE_CATEGORY_RESET: 'CREATE_CATEGORY_RESET',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_ERROR: 'CREATE_CATEGORY_ERROR',

    CREATE_SUB_CATEGORY: 'CREATE_SUB_CATEGORY',
    CREATE_SUB_CATEGORY_LOADING: 'CREATE_SUB_CATEGORY_LOADING',
    CREATE_SUB_CATEGORY_RESET: 'CREATE_SUB_CATEGORY_RESET',
    CREATE_SUB_CATEGORY_SUCCESS: 'CREATE_SUB_CATEGORY_SUCCESS',
    CREATE_SUB_CATEGORY_ERROR: 'CREATE_SUB_CATEGORY_ERROR',

    UPDATE_CATEGORY_DATA_FIRST: '@@auth/UPDATE_CATEGORY_DATA_FIRST',
    UPDATE_CATEGORY_DATA_LOADING: '@@auth/UPDATE_CATEGORY_DATA_LOADING',
    UPDATE_CATEGORY_DATA_SUCCESS: '@@auth/UPDATE_CATEGORY_DATA_SUCCESS',
    UPDATE_CATEGORY_DATA_RESET: '@@auth/UPDATE_CATEGORY_DATA_RESET',
    UPDATE_CATEGORY_DATA_ERROR: '@@auth/UPDATE_CATEGORY_DATA_ERROR',

    DELETE_CATEGORY_DATA_FIRST: '@@auth/DELETE_CATEGORY_DATA_FIRST',
    DELETE_CATEGORY_DATA_LOADING: '@@auth/DELETE_CATEGORY_DATA_LOADING',
    DELETE_CATEGORY_DATA_SUCCESS: '@@auth/DELETE_CATEGORY_DATA_SUCCESS',
    DELETE_CATEGORY_DATA_RESET: '@@auth/DELETE_CATEGORY_DATA_RESET',
    DELETE_CATEGORY_DATA_ERROR: '@@auth/DELETE_CATEGORY_DATA_ERROR',

    GET_ALL_CATEGORY: 'GET_ALL_CATEGORY',
    GET_ALL_CATEGORY_LOADING: 'GET_ALL_CATEGORY_LOADING',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_RESET: 'GET_ALL_CATEGORY_RESET',
    GET_ALL_CATEGORY_ERROR: 'GET_ALL_CATEGORY_ERROR',

    STATE_EMPTY_FIRST: '@@auth/STATE_EMPTY_FIRST',
    STATE_EMPTY_SUCCESS: '@@auth/STATE_EMPTY_SUCCESS',
};
