export const GET_SERVICES_REQUEST = 'GET_SERVICES_REQUEST';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_SERVICES_FAILURE = 'GET_SERVICES_FAILURE';

export const ADD_SERVICES_REQUEST = 'ADD_SERVICES_REQUEST';
export const ADD_SERVICES_SUCCESS = 'ADD_SERVICES_SUCCESS';
export const ADD_SERVICES_FAILURE = 'ADD_SERVICES_FAILURE';

export const UPDATE_SERVICES_REQUEST = 'UPDATE_SERVICES_REQUEST';
export const UPDATE_SERVICES_SUCCESS = 'UPDATE_SERVICES_SUCCESS';
export const UPDATE_SERVICES_FAILURE = 'UPDATE_SERVICES_FAILURE';

export const DELETE_SERVICES_REQUEST = 'DELETE_SERVICES_REQUEST';
export const DELETE_SERVICES_SUCCESS = 'DELETE_SERVICES_SUCCESS';
export const DELETE_SERVICES_FAILURE = 'DELETE_SERVICES_FAILURE';