const OrderActionTypes = {

    // start list 
    GET_ORDER_LIST: '@@LOCATION/GET_ORDER_LIST',
    ORDER_LIST_LOADING: '@@LOCATION/ORDER_LIST/LOADING',
    ORDER_LIST_SUCCESS: '@@LOCATION/ORDER_LIST/SUCESS',
    ORDER_LIST_ERROR: '@@LOCATION/ORDER_LIST/ERROR',


    // start create 
    CREATE_ORDER: '@@CREATE_ORDER',
    ORDER_CREATE_LOADING: '@@ORDER_CREATE/LOADING',
    ORDER_CREATE_SUCESS: '@@ORDER_CREATE/SUCESS',
    ORDER_CREATE_ERROR: '@@ORDER_CREATE/ERROR',


    // start update 
    UPDATE_ORDER: '@@UPDATE_ORDER',
    ORDER_UPDATE_LOADING: '@@ORDER_UPDATE/LOADING',
    ORDER_UPDATE_SUCESS: '@@ORDER_UPDATE/SUCESS',
    ORDER_UPDATE_ERROR: '@@ORDER_UPDATE/ERROR',


    // start details 
    DETAILS_ORDER: '@@ORDER_EMPLOYEE',
    ORDER_DETAILS_LOADING: '@@ORDER_DETAILS/LOADING',
    ORDER_DETAILS_SUCESS: '@@ORDER_DETAILS/SUCESS',
    ORDER_DETAILS_ERROR: '@@ORDER_DETAILS/ERROR',

}
export default OrderActionTypes