export const buyer = {
    GET_PURCHASE_ORDER_DETAILS_FOR_ADMIN: 'GET_PURCHASE_ORDER_DETAILS_FOR_ADMIN',
    GET_PURCHASE_ORDER_DETAILS_FOR_ADMIN_SUCCESS: 'GET_PURCHASE_ORDER_DETAILS_FOR_ADMIN_SUCCESS',
    GET_PURCHASE_ORDER_DETAILS_FOR_ADMIN_FAILURE: 'GET_PURCHASE_ORDER_DETAILS_FOR_ADMIN_FAILURE',
    GET_PURCHASE_ORDER_DETAILS_FOR_ADMIN_LOADING: 'GET_PURCHASE_ORDER_DETAILS_FOR_ADMIN_LOADING',
    GET_PURCHASE_ORDER_DETAILS_FOR_ADMIN_RESET: 'GET_PURCHASE_ORDER_DETAILS_FOR_ADMIN_RESET',
};
