//------------------------------------C O N S T A N T S----------------------------------------------
export const FaqActionTypes = {
    FAQ_DATA_FIRST: '@@auth/FAQ_DATA_FIRST',
    FAQ_DATA_LOADING: '@@auth/FAQ_DATA_LOADING',
    FAQ_DATA_SUCCESS: '@@auth/FAQ_DATA_SUCCESS',
    FAQ_DATA_ERROR: '@@auth/FAQ_DATA_ERROR',
    FAQ_DATA_RESET: '@@auth/FAQ_DATA_RESET',

    CREATE_FAQ_FIRST: '@@auth/CREATE_FAQ_FIRST',
    CREATE_FAQ_LOADING: '@@auth/CREATE_FAQ_LOADING',
    CREATE_FAQ_SUCCESS: '@@auth/CREATE_FAQ_SUCCESS',
    CREATE_FAQ_ERROR: '@@auth/CREATE_FAQ_ERROR',

    UPDATE_FAQ_DATA_FIRST: '@@auth/UPDATE_FAQ_DATA_FIRST',
    UPDATE_FAQ_DATA_LOADING: '@@auth/UPDATE_FAQ_DATA_LOADING',
    UPDATE_FAQ_DATA_SUCCESS: '@@auth/UPDATE_FAQ_DATA_SUCCESS',
    UPDATE_FAQ_DATA_RESET: '@@auth/UPDATE_FAQ_DATA_RESET',
    UPDATE_FAQ_DATA_ERROR: '@@auth/UPDATE_FAQ_DATA_ERROR',

    DELETE_FAQ_DATA_FIRST: '@@auth/DELETE_FAQ_DATA_FIRST',
    DELETE_FAQ_DATA_LOADING: '@@auth/DELETE_FAQ_DATA_LOADING',
    DELETE_FAQ_DATA_SUCCESS: '@@auth/DELETE_FAQ_DATA_SUCCESS',
    DELETE_FAQ_DATA_RESET: '@@auth/DELETE_FAQ_DATA_RESET',
    DELETE_FAQ_DATA_ERROR: '@@auth/DELETE_FAQ_DATA_ERROR',

    STATE_EMPTY_FIRST: '@@auth/STATE_EMPTY_FIRST',
    STATE_EMPTY_SUCCESS: '@@auth/STATE_EMPTY_SUCCESS',

};