//------------------------------------C O N S T A N T S----------------------------------------------
export const DashboardActionTypes = {
    DASHBOARD_DATA_FIRST: '@@dashboard/DASHBOARD_DATA_FIRST',
    DASHBOARD_DATA_LOADING: '@@dashboard/DASHBOARD_DATA_LOADING',
    DASHBOARD_DATA_SUCCESS: '@@dashboard/DASHBOARD_DATA_SUCCESS',
    DASHBOARD_DATA_ERROR: '@@dashboard/DASHBOARD_DATA_ERROR',
    DASHBOARD_DATA_RESET: '@@dashboard/DASHBOARD_DATA_RESET',

    RECENT_REGISTRATIONS_FOR_DASHBOARD: 'RECENT_REGISTRATIONS_FOR_DASHBOARD',
    RECENT_REGISTRATIONS_FOR_DASHBOARD_LOADING: 'RECENT_REGISTRATIONS_FOR_DASHBOARD_LOADING',
    RECENT_REGISTRATIONS_FOR_DASHBOARD_SUCCESS: 'RECENT_REGISTRATIONS_FOR_DASHBOARD_SUCCESS',
    RECENT_REGISTRATIONS_FOR_DASHBOARD_ERROR: 'RECENT_REGISTRATIONS_FOR_DASHBOARD_ERROR',
    RECENT_REGISTRATIONS_FOR_DASHBOARD_RESET: 'RECENT_REGISTRATIONS_FOR_DASHBOARD_RESET',
};
