export const TransactionActionTypes = {

    GET_PAID_AUCTION_DATA_FIRST: '@transactions/GET_PAID_AUCTION_DATA_FIRST',
    GET_PAID_AUCTION_DATA_LOADING: '@transactions/GET_PAID_AUCTION_DATA_LOADING',
    GET_PAID_AUCTION_DATA_SUCCESS: '@transactions/GET_PAID_AUCTION_DATA_SUCCESS',
    GET_PAID_AUCTION_DATA_ERROR: '@transactions/GET_PAID_AUCTION_DATA_ERROR',

    GET_NON_PAID_AUCTION_DATA_FIRST: '@transactions/GET_NON_PAID_AUCTION_DATA_FIRST',
    GET_NON_PAID_AUCTION_DATA_LOADING: '@transactions/GET_NON_PAID_AUCTION_DATA_LOADING',
    GET_NON_PAID_AUCTION_DATA_SUCCESS: '@transactions/GET_NON_PAID_AUCTION_DATA_SUCCESS',
    GET_NON_PAID_AUCTION_DATA_ERROR: '@transactions/GET_NON_PAID_AUCTION_DATA_ERROR',

}