export const GET_TEAMS_REQUEST = 'GET_TEAMS_REQUEST';
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const GET_TEAMS_FAILURE = 'GET_TEAMS_FAILURE';

export const ADD_TEAMS_REQUEST = 'ADD_TEAMS_REQUEST';
export const ADD_TEAMS_SUCCESS = 'ADD_TEAMS_SUCCESS';
export const ADD_TEAMS_FAILURE = 'ADD_TEAMS_FAILURE';

export const UPDATE_TEAMS_REQUEST = 'UPDATE_TEAMS_REQUEST';
export const UPDATE_TEAMS_SUCCESS = 'UPDATE_TEAMS_SUCCESS';
export const UPDATE_TEAMS_FAILURE = 'UPDATE_TEAMS_FAILURE';

export const DELETE_TEAMS_REQUEST = 'DELETE_TEAMS_REQUEST';
export const DELETE_TEAMS_SUCCESS = 'DELETE_TEAMS_SUCCESS';
export const DELETE_TEAMS_FAILURE = 'DELETE_TEAMS_FAILURE';