const ProductBrandActionTypes = {

    // start list 
    GET_BRAND_LIST: '@@GET_BRAND_LIST',
    BRAND_LIST_LOADING: '@@BRAND_LIST/LOADING',
    BRAND_LIST_SUCCESS: '@@BRAND_LIST/SUCESS',
    BRAND_LIST_ERROR: '@@BRAND_LIST/ERROR',


    // start create 
    CREATE_BRAND: '@@CREATE_BRAND',
    BRAND_CREATE_LOADING: '@@BRAND_CREATE/LOADING',
    BRAND_CREATE_SUCESS: '@@BRAND_CREATE/SUCESS',
    BRAND_CREATE_ERROR: '@@BRAND_CREATE/ERROR',


    // // start update 
    UPDATE_BRAND: '@@UPDATE_BRAND',
    BRAND_UPDATE_LOADING: '@@BRAND_UPDATE/LOADING',
    BRAND_UPDATE_SUCESS: '@@BRAND_UPDATE/SUCESS',
    BRAND_UPDATE_ERROR: '@@BRAND_UPDATE/ERROR',

}

export default ProductBrandActionTypes
