//------------------------------------C O N S T A N T S----------------------------------------------
export const LeadActionTypes = {
    AUCTION_LEAD_FIRST: '@@auctionLead/AUCTION_LEAD_FIRST',
    AUCTION_LEAD_LOADING: '@@auctionLead/AUCTION_LEAD_LOADING',
    AUCTION_LEAD_SUCCESS: '@@auctionLead/AUCTION_LEAD_SUCCESS',
    AUCTION_LEAD_ERROR: '@@auctionLead/AUCTION_LEAD_ERROR',

    GET_SOLD_PRODUCT_DETAILS_FIRST: '@@auctionLead/GET_SOLD_PRODUCT_DETAILS_FIRST',
    GET_SOLD_PRODUCT_DETAILS_LOADING: '@@auctionLead/GET_SOLD_PRODUCT_DETAILS_LOADING',
    GET_SOLD_PRODUCT_DETAILS_SUCCESS: '@@auctionLead/GET_SOLD_PRODUCT_DETAILS_SUCCESS',
    GET_SOLD_PRODUCT_DETAILS_ERROR: '@@auctionLead/GET_SOLD_PRODUCT_DETAILS_ERROR',

    GET_LIVE_BIDS_FIRST: '@@auctionLead/GET_LIVE_BIDS_FIRST',
    GET_LIVE_BIDS_LOADING: '@@auctionLead/GET_LIVE_BIDS_LOADING',
    GET_LIVE_BIDS_SUCCESS: '@@auctionLead/GET_LIVE_BIDS_SUCCESS',
    GET_LIVE_BIDS_ERROR: '@@auctionLead/GET_LIVE_BIDS_ERROR',
    
    AUCTION_LEAD_RESET: '@@auctionLead/AUCTION_LEAD_RESET',
};