export const bidHandler = {
    GET_BID_HANDLER: 'GET_BID_HANDLER',
    GET_BID_HANDLER_SUCCESS: 'GET_BID_HANDLER_SUCCESS',
    GET_BID_HANDLER_ERROR: 'GET_BID_HANDLER_ERROR',
    GET_BID_HANDLER_RESET: 'GET_BID_HANDLER_RESET',
    GET_BID_HANDLER_LOADING: 'GET_BID_HANDLER_LOADING',

    POST_BID_HANDLER: 'POST_BID_HANDLER',
    POST_BID_HANDLER_SUCCESS: 'POST_BID_HANDLER_SUCCESS',
    POST_BID_HANDLER_ERROR: 'POST_BID_HANDLER_ERROR',
    POST_BID_HANDLER_RESET: 'POST_BID_HANDLER_RESET',
    POST_BID_HANDLER_LOADING: 'POST_BID_HANDLER_LOADING',

    EDIT_BID_HANDLER: 'EDIT_BID_HANDLER',
    EDIT_BID_HANDLER_SUCCESS: 'EDIT_BID_HANDLER_SUCCESS',
    EDIT_BID_HANDLER_ERROR: 'EDIT_BID_HANDLER_ERROR',
    EDIT_BID_HANDLER_RESET: 'EDIT_BID_HANDLER_RESET',
    EDIT_BID_HANDLER_LOADING: 'EDIT_BID_HANDLER_LOADING',

    DELETE_BID_HANDLER: 'DELETE_BID_HANDLER',
    DELETE_BID_HANDLER_SUCCESS: 'DELETE_BID_HANDLER_SUCCESS',
    DELETE_BID_HANDLER_ERROR: 'DELETE_BID_HANDLER_ERROR',
    DELETE_BID_HANDLER_RESET: 'DELETE_BID_HANDLER_RESET',
    DELETE_BID_HANDLER_LOADING: 'DELETE_BID_HANDLER_LOADING',
};
