export const SupportActionTypes = {

    GET_TICKETS_FIRST: '@@/support/GET_TICKETS_FIRST',
    GET_TICKETS_LOADING: '@@/support/GET_TICKETS_LOADING',
    GET_TICKETS_SUCCESS: '@@/support/GET_TICKETS_SUCCESS',
    GET_TICKETS_ERROR: '@@/support/GET_TICKETS_ERROR',

    GET_CHAT_BY_ID_FIRST: '@@/support/GET_CHAT_BY_ID_FIRST',
    GET_CHAT_ID_LOADING: '@@/support/GET_CHAT_BY_ID_LOADING',
    GET_CHAT_BY_ID_SUCCESS: '@@/support/GET_CHAT_BY_ID_SUCCESS',
    GET_CHAT_BY_ID_ERROR: '@@/support/GET_CHAT_BY_ID_ERROR',
    GET_CHAT_BY_ID_RESET: '@@/support/GET_CHAT_BY_ID_RESET',

    CREATE_TICKETS_FIRST: '@@/support/CREATE_TICKETS_FIRST',
    CREATE_TICKETS_LOADING: '@@/support/CREATE_TICKETS_LOADING',
    CREATE_TICKETS_SUCCESS: '@@/support/CREATE_TICKETS_SUCCESS',
    CREATE_TICKETS_ERROR: '@@/support/CREATE_TICKETS_ERROR',

    UPDATE_TICKETS_FIRST: '@@/support/UPDATE_TICKETS_FIRST',
    UPDATE_TICKETS_LOADING: '@@/support/UPDATE_TICKETS_LOADING',
    UPDATE_TICKETS_SUCCESS: '@@/support/UPDATE_TICKETS_SUCCESS',
    UPDATE_TICKETS_ERROR: '@@/support/UPDATE_TICKETS_ERROR',

    RESET_TICKETS: '@@/support/RESET_TICKETS',
}