export const comissionActionTypes={

    GET_COMMISSION_DATA_FIRST:"@comission/GET_COMMISSION_DATA_FIRST",
    GET_COMMISSION_DATA_LOADING:"@comission/GET_COMMISSION_DATA_LOADING",
    GET_COMMISSION_DATA_SUCCESS:"@comission/GET_COMMISSION_DATA_SUCCESS",
    GET_COMMISSION_DATA_ERROR:"@comission/GET_COMMISSION_DATA_ERROR",

    CREATE_COMMISSION_DATA_FIRST:"@comission/CREATE_COMMISSION_DATA_FIRST",
    CREATE_COMMISSION_DATA_LOADING:"@comission/CREATE_COMMISSION_DATA_LOADING",
    CREATE_COMMISSION_DATA_SUCCESS:"@comission/CREATE_COMMISSION_DATA_SUCCESS",
    CREATE_COMMISSION_DATA_ERROR:"@comission/CREATE_COMMISSION_DATA_ERROR",

    UPDATE_COMMISSION_DATA_FIRST:"@comission/UPDATE_COMMISSION_DATA_FIRST",
    UPDATE_COMMISSION_DATA_LOADING:"@comission/UPDATE_COMMISSION_DATA_LOADING",
    UPDATE_COMMISSION_DATA_SUCCESS:"@comission/UPDATE_COMMISSION_DATA_SUCCESS",
    UPDATE_COMMISSION_DATA_ERROR:"@comission/UPDATE_COMMISSION_DATA_ERROR",

    RESET_COMMISSION_DATA:"@comission/RESET_COMMISSION_DATA",
}