//------------------------------------C O N S T A N T S----------------------------------------------
export const SupportActionTypes = {
    GET_SUPPORT_DATA_FIRST: '@@auth/GET_SUPPORT_DATA_FIRST',
    GET_SUPPORT_DATA_LOADING: '@@auth/GET_SUPPORT_DATA_LOADING',
    GET_SUPPORT_DATA_SUCCESS: '@@auth/GET_SUPPORT_DATA_SUCCESS',
    GET_SUPPORT_DATA_ERROR: '@@auth/GET_SUPPORT_DATA_ERROR',
    
    UPDATE_SUPPORT_DATA_FIRST: '@@auth/UPDATE_SUPPORT_DATA_FIRST',
    UPDATE_SUPPORT_DATA_LOADING: '@@auth/UPDATE_SUPPORT_DATA_LOADING',
    UPDATE_SUPPORT_DATA_SUCCESS: '@@auth/UPDATE_SUPPORT_DATA_SUCCESS',
    UPDATE_SUPPORT_DATA_ERROR: '@@auth/UPDATE_SUPPORT_DATA_ERROR',
    
    SUPPORT_DATA_RESET: '@@auth/GET_SUPPORT_DATA_RESET',
};