export const GET_LATEST_NEWS_REQUEST = 'GET_LATEST_NEWS_REQUEST';
export const GET_LATEST_NEWS_SUCCESS = 'GET_LATEST_NEWS_SUCCESS';
export const GET_LATEST_NEWS_FAILURE = 'GET_LATEST_NEWS_FAILURE';

export const ADD_LATEST_NEWS_REQUEST = 'ADD_LATEST_NEWS_REQUEST';
export const ADD_LATEST_NEWS_SUCCESS = 'ADD_LATEST_NEWS_SUCCESS';
export const ADD_LATEST_NEWS_FAILURE = 'ADD_LATEST_NEWS_FAILURE';

export const EDIT_LATEST_NEWS_REQUEST = 'EDIT_LATEST_NEWS_REQUEST';
export const EDIT_LATEST_NEWS_SUCCESS = 'EDIT_LATEST_NEWS_SUCCESS';
export const EDIT_LATEST_NEWS_FAILURE = 'EDIT_LATEST_NEWS_FAILURE';

export const DELETE_LATEST_NEWS_REQUEST = 'DELETE_LATEST_NEWS_REQUEST';
export const DELETE_LATEST_NEWS_SUCCESS = 'DELETE_LATEST_NEWS_SUCCESS';
export const DELETE_LATEST_NEWS_FAILURE = 'DELETE_LATEST_NEWS_FAILURE';