const AssignedPackageActionTypes = {

    // start list 
    GET_ASSIGNED_PACKAGE_LIST: '@@GET_ASSIGNED_PACKAGE_LIST',
    ASSIGNED_PACKAGE_LIST_LOADING: '@@ASSIGNED_PACKAGE_LIST/LOADING',
    ASSIGNED_PACKAGE_LIST_SUCCESS: '@@ASSIGNED_PACKAGE_LIST/SUCESS',
    ASSIGNED_PACKAGE_LIST_ERROR: '@@ASSIGNED_PACKAGE_LIST/ERROR',


    // start create 
    CREATE_ASSIGNED_PACKAGE: '@@CREATE_ASSIGNED_PACKAGE',
    ASSIGNED_PACKAGE_CREATE_LOADING: '@@ASSIGNED_PACKAGE_CREATE/LOADING',
    ASSIGNED_PACKAGE_CREATE_SUCESS: '@@ASSIGNED_PACKAGE_CREATE/SUCESS',
    ASSIGNED_PACKAGE_CREATE_ERROR: '@@ASSIGNED_PACKAGE_CREATE/ERROR',


    // start update 
    UPDATE_ASSIGNED_PACKAGE: '@@UPDATE_ASSIGNED_P   ACKAGE',
    ASSIGNED_PACKAGE_UPDATE_LOADING: '@@ASSIGNED_PACKAGE_UPDATE/LOADING',
    ASSIGNED_PACKAGE_UPDATE_SUCESS: '@@ASSIGNED_PACKAGE_UPDATE/SUCESS',
    ASSIGNED_PACKAGE_UPDATE_ERROR: '@@ASSIGNED_PACKAGE_UPDATE/ERROR',


    // start details 
    DETAILS_ASSIGNED_PACKAGE: '@@UPDATE_ASSIGNED_PACKAGE',
    ASSIGNED_PACKAGE_DETAILS_LOADING: '@@ASSIGNED_PACKAGE_DETAILS/LOADING',
    ASSIGNED_PACKAGE_DETAILS_SUCESS: '@@ASSIGNED_PACKAGE_DETAILS/SUCESS',
    ASSIGNED_PACKAGE_DETAILS_ERROR: '@@ASSIGNED_PACKAGE_DETAILS/ERROR',

}
export default AssignedPackageActionTypes