const EmployeeActionTypes = {

    // start list 
    GET_EMPLOYEE_LIST: '@@GET_EMPLOYEE_LIST',
    EMPLOYEE_LIST_LOADING: '@@EMPLOYEE_LIST/LOADING',
    EMPLOYEE_LIST_SUCCESS: '@@EMPLOYEE_LIST/SUCESS',
    EMPLOYEE_LIST_ERROR: '@@EMPLOYEE_LIST/ERROR',


    // start create 
    CREATE_EMPLOYEE: '@@CREATE_EMPLOYEE',
    EMPLOYEE_CREATE_LOADING: '@@EMPLOYEE_CREATE/LOADING',
    EMPLOYEE_CREATE_SUCESS: '@@EMPLOYEE_CREATE/SUCESS',
    EMPLOYEE_CREATE_ERROR: '@@EMPLOYEE_CREATE/ERROR',


    // start update 
    UPDATE_EMPLOYEE: '@@UPDATE_EMPLOYEE',
    EMPLOYEE_UPDATE_LOADING: '@@EMPLOYEE_UPDATE/LOADING',
    EMPLOYEE_UPDATE_SUCESS: '@@EMPLOYEE_UPDATE/SUCESS',
    EMPLOYEE_UPDATE_ERROR: '@@EMPLOYEE_UPDATE/ERROR',


    // start details 
    DETAILS_EMPLOYEE: '@@DETAILS_EMPLOYEE',
    EMPLOYEE_DETAILS_LOADING: '@@EMPLOYEE_DETAILS/LOADING',
    EMPLOYEE_DETAILS_SUCESS: '@@EMPLOYEE_DETAILS/SUCESS',
    EMPLOYEE_DETAILS_ERROR: '@@EMPLOYEE_DETAILS/ERROR',
    EMPLOYEE_DETAILS_RESET: '@@EMPLOYEE_DETAILS/RESET',

}
export default EmployeeActionTypes