//------------------------------------C O N S T A N T S----------------------------------------------
export const NotificationActionTypes = {
    GET_NOTIFICATION_FIRST: '@@notification/GET_NOTIFICATION_FIRST',
    GET_NOTIFICATION_LOADING: '@@notification/GET_NOTIFICATION_LOADING',
    GET_NOTIFICATION_SUCCESS: '@@notification/GET_NOTIFICATION_SUCCESS',
    GET_NOTIFICATION_ERROR: '@@notification/GET_NOTIFICATION_ERROR',

    GET_NOTIFICATION_BY_ADMIN: 'GET_NOTIFICATION_BY_ADMIN',
    GET_NOTIFICATION_BY_ADMIN_LOADING: 'GET_NOTIFICATION_BY_ADMIN_LOADING',
    GET_NOTIFICATION_BY_ADMIN_SUCCESS: 'GET_NOTIFICATION_BY_ADMIN_SUCCESS',
    GET_NOTIFICATION_BY_ADMIN_ERROR: 'GET_NOTIFICATION_BY_ADMIN_ERROR',

    CREATE_NOTIFICATION_FIRST: '@@notification/CREATE_NOTIFICATION_FIRST',
    CREATE_NOTIFICATION_LOADING: '@@notification/CREATE_NOTIFICATION_LOADING',
    CREATE_NOTIFICATION_SUCCESS: '@@notification/CREATE_NOTIFICATION_SUCCESS',
    CREATE_NOTIFICATION_ERROR: '@@notification/CREATE_NOTIFICATION_ERROR',

    UPDATE_NOTIFICATION_DATA_FIRST: '@@notification/UPDATE_NOTIFICATION_DATA_FIRST',
    UPDATE_NOTIFICATION_DATA_LOADING: '@@notification/UPDATE_NOTIFICATION_DATA_LOADING',
    UPDATE_NOTIFICATION_DATA_SUCCESS: '@@notification/UPDATE_NOTIFICATION_DATA_SUCCESS',
    UPDATE_NOTIFICATION_DATA_RESET: '@@notification/UPDATE_NOTIFICATION_DATA_RESET',
    UPDATE_NOTIFICATION_DATA_ERROR: '@@notification/UPDATE_NOTIFICATION_DATA_ERROR',

    STATE_EMPTY_FIRST: '@@notification/STATE_EMPTY_FIRST',
    STATE_EMPTY_SUCCESS: '@@notification/STATE_EMPTY_SUCCESS',
};
