const PackageActionTypes = {

    // start list 
    GET_PACKAGE_LIST: '@@GET_PACKAGE_LIST',
    PACKAGE_LIST_LOADING: '@@PACKAGE_LIST/LOADING',
    PACKAGE_LIST_SUCCESS: '@@PACKAGE_LIST/SUCESS',
    PACKAGE_LIST_ERROR: '@@PACKAGE_LIST/ERROR',


    // start create 
    CREATE_PACKAGE: '@@CREATE_PACKAGE',
    PACKAGE_CREATE_LOADING: '@@PACKAGE_CREATE/LOADING',
    PACKAGE_CREATE_SUCESS: '@@PACKAGE_CREATE/SUCESS',
    PACKAGE_CREATE_ERROR: '@@PACKAGE_CREATE/ERROR',


    // start update 
    UPDATE_PACKAGE: '@@UPDATE_PACKAGE',
    PACKAGE_UPDATE_LOADING: '@@PACKAGE_UPDATE/LOADING',
    PACKAGE_UPDATE_SUCESS: '@@PACKAGE_UPDATE/SUCESS',
    PACKAGE_UPDATE_ERROR: '@@PACKAGE_UPDATE/ERROR',


    // start details 
    DETAILS_PACKAGE: '@@UPDATE_PACKAGE',
    PACKAGE_DETAILS_LOADING: '@@PACKAGE_DETAILS/LOADING',
    PACKAGE_DETAILS_SUCESS: '@@PACKAGE_DETAILS/SUCESS',
    PACKAGE_DETAILS_ERROR: '@@PACKAGE_DETAILS/ERROR',

}
export default PackageActionTypes