//------------------------------------C O N S T A N T S----------------------------------------------
export const ProductActionTypes = {
    PRODUCT_DATA_FIRST: '@@auth/PRODUCT_DATA_FIRST',
    PRODUCT_DATA_LOADING: '@@auth/PRODUCT_DATA_LOADING',
    PRODUCT_DATA_SUCCESS: '@@auth/PRODUCT_DATA_SUCCESS',
    PRODUCT_DATA_ERROR: '@@auth/PRODUCT_DATA_ERROR',
    PRODUCT_DATA_RESET: '@@auth/PRODUCT_DATA_RESET',

    SPECIFIC_PRODUCT_DATA: 'SPECIFIC_PRODUCT_DATA',
    SPECIFIC_PRODUCT_DATA_LOADING: 'SPECIFIC_PRODUCT_DATA_LOADING',
    SPECIFIC_PRODUCT_DATA_SUCCESS: 'SPECIFIC_PRODUCT_DATA_SUCCESS',
    SPECIFIC_PRODUCT_DATA_ERROR: 'SPECIFIC_PRODUCT_DATA_ERROR',
    SPECIFIC_PRODUCT_DATA_RESET: 'SPECIFIC_PRODUCT_DATA_RESET',

    CREATE_PRODUCT_FIRST: '@@auth/CREATE_PRODUCT_FIRST',
    CREATE_PRODUCT_LOADING: '@@auth/CREATE_PRODUCT_LOADING',
    CREATE_PRODUCT_SUCCESS: '@@auth/CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_ERROR: '@@auth/CREATE_PRODUCT_ERROR',

    UPDATE_PRODUCT_DATA_FIRST: '@@auth/UPDATE_PRODUCT_DATA_FIRST',
    UPDATE_PRODUCT_DATA_LOADING: '@@auth/UPDATE_PRODUCT_DATA_LOADING',
    UPDATE_PRODUCT_DATA_SUCCESS: '@@auth/UPDATE_PRODUCT_DATA_SUCCESS',
    UPDATE_PRODUCT_DATA_RESET: '@@auth/UPDATE_PRODUCT_DATA_RESET',
    UPDATE_PRODUCT_DATA_ERROR: '@@auth/UPDATE_PRODUCT_DATA_ERROR',

    DELETE_PRODUCT_DATA_FIRST: '@@auth/DELETE_PRODUCT_DATA_FIRST',
    DELETE_PRODUCT_DATA_LOADING: '@@auth/DELETE_PRODUCT_DATA_LOADING',
    DELETE_PRODUCT_DATA_SUCCESS: '@@auth/DELETE_PRODUCT_DATA_SUCCESS',
    DELETE_PRODUCT_DATA_RESET: '@@auth/DELETE_PRODUCT_DATA_RESET',
    DELETE_PRODUCT_DATA_ERROR: '@@auth/DELETE_PRODUCT_DATA_ERROR',

    STATE_EMPTY_FIRST: '@@auth/STATE_EMPTY_FIRST',
    STATE_EMPTY_SUCCESS: '@@auth/STATE_EMPTY_SUCCESS',
};
