export const LocationActionTypes = {

    GET_ALL_STATES_FIRST: '@@/location/GET_ALL_STATES_FIRST',
    GET_ALL_STATES_LOADING: '@@/location/GET_ALL_STATES_LOADING',
    GET_ALL_STATES_SUCCESS: '@@/location/GET_ALL_STATES_SUCCESS',
    GET_ALL_STATES_ERROR: '@@/location/GET_ALL_STATES_ERROR',

    GET_CITIES_BY_ID_FIRST: '@@/location/GET_CITIES_BY_ID_FIRST',
    GET_CITIES_BY_ID_LOADING: '@@/location/GET_CITIES_BY_ID_LOADING',
    GET_CITIES_BY_ID_SUCCESS: '@@/location/GET_CITIES_BY_ID_SUCCESS',
    GET_CITIES_BY_ID_ERROR: '@@/location/GET_CITIES_BY_ID_ERROR',
    GET_CITIES_BY_ID_RESET: '@@/location/GET_CITIES_BY_ID_RESET',

    CREATE_LOCATION_FIRST: '@@/location/CREATE_LOCATION_FIRST',
    CREATE_LOCATION_LOADING: '@@/location/CREATE_LOCATION_LOADING',
    CREATE_LOCATION_SUCCESS: '@@/location/CREATE_LOCATION_SUCCESS',
    CREATE_LOCATION_ERROR: '@@/location/CREATE_LOCATION_ERROR',

    UPDATE_CITY_FIRST: '@@/location/UPDATE_CITY_FIRST',
    UPDATE_CITY_LOADING: '@@/location/UPDATE_CITY_LOADING',
    UPDATE_CITY_SUCCESS: '@@/location/UPDATE_CITY_SUCCESS',
    UPDATE_CITY_ERROR: '@@/location/UPDATE_CITY_ERROR',

    UPDATE_LOCATION_FIRST: '@@/location/UPDATE_LOCATION_FIRST',
    UPDATE_LOCATION_LOADING: '@@/location/UPDATE_LOCATION_LOADING',
    UPDATE_LOCATION_SUCCESS: '@@/location/UPDATE_LOCATION_SUCCESS',
    UPDATE_LOCATION_ERROR: '@@/location/UPDATE_LOCATION_ERROR',

    RESET_LOCATION: '@@/location/RESET_LOCATION',
}